### ISSUE TITLE
More than 4 PWM fan 25Khz ? 

### ISSUE THREAD

**Issue by Lemania** [AL-FC/AL-FanControl#2]
Hi
you managed to control more than 4 fan at 25khz ?

thanks
Best regards
Sébastien

**Comment by Bengt** [comment]
Yes. I had up to 8 fans running over PWM.

**Comment by Lemania** [comment]
Super ! 

I will look in detail and download fritzing to see your schematic

thanks to your work
Best regard
Sébastien

**Comment by Bengt** [comment]
Thanks for your interest in this. I do not use the fan controller anymore, so the code has gone stale. Anyway, I just pushed the latest version I was using until about half a year ago.

**Comment by Lemania** [comment]
Thanks,  I have an nzxt grid-plus-v3 and I do not like the CAM app

I have two xeon,16 core and CAM does not allow to choose the CPU that you want, or even take a temperature average on the core or the package. So the fans fluctuates... 

I also noticed that CAM was using a lot of bandwidth, and we do not know exactly which data is going through

**Comment by Lemania** [comment]
so you no longer use transtor in the latest version ?

**Comment by Bengt** [comment]
Yes, I think the output buffering is unnecessary.

Lemania <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 13:02:

**Comment by Bengt** [comment]
Interesting that CAM tends to oscillate the fan speed for you. I managed to run into oscillation with my new motherboard (X399 Taichi), too. Maybe I can still benefit from a stand-alone fan controller ...

I used this on an AMD Phenom II X6, so you will have to adapt the sensor data parsing to fit your machine.

Feel free to send me pull requests for any changes you make to the source code.

**Comment by Bengt** [comment]
I used an Arduino Pro Micro Clone off Aliexpress. Just like this one:

https://de.aliexpress.com/item//32860810419.html

**Comment by Lemania** [comment]
Hello, I resume the project after a break, I now have a mega32u4.

You did not answer a question, you get out 25khz on each output ?

thanks
best regards
Sébastien

**Comment by Bengt** [comment]
Sorry for replying only now. I just looked into that for a different reason. None of the analog outputs can provide exactly 25 kHz. However, you can configure all of the analog outputs to generate either 31250 or 7813 Hz, both of which are sufficiently close to the PWM specification for all fans I tested, at least. For details on how to do that, please refer to the source code documentation in this file:

https://github.com/AL-FC/AL-FanControl/blob/master/arduino/bridgehead2/bridgehead3_Mega_v5.0.7/bridgehead3_Mega_v5.0.7/bridgehead3_Mega_v5.0.7.ino

**Comment by Bengt** [comment]
With that, I feel like this question is answered and actually implemented in working code for the microcontroller in the scope of this project. Therefore, I am closing this issue.
